using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Content.Client.UserInterface.Controls;

namespace Content.Client.MassMedia.Ui._Persistence14;

[GenerateTypedNameReferences]
public sealed partial class BookPublisherWindow : FancyWindow
{
    public BookPublisherWindow()
    {
        RobustXamlLoader.Load(this);
        PublishButton.OnPressed += OnPublishClicked;
        EjectButton.OnPressed += OnEjectClicked;
    }

    public string TitleInputText => TitleInput.Text;

    public event Action<string>? PublishButtonPressed;
    public event Action? EjectButtonPressed;

    private void OnPublishClicked(BaseButton.ButtonEventArgs e)
    {
        PublishButtonPressed?.Invoke(TitleInputText);
    }

    private void OnEjectClicked(BaseButton.ButtonEventArgs e)
    {
        EjectButtonPressed?.Invoke();
    }

    public void UpdateUI(bool bookInserted, string bookName, bool canPublish)
    {
        if (bookInserted)
            BookStatus.Text = Loc.GetString("book-publisher-book-inserted", ("name", bookName));
        else
            BookStatus.Text = Loc.GetString("book-publisher-no-book");

        PublishButton.Disabled = !canPublish || !bookInserted;
        EjectButton.Disabled = !bookInserted;
    }
}
