- type: entity
  parent: BaseItem
  id: GridConfigurator
  name: grid configurator
  description: Used to modify the name and station that a grid is associated with.
  components:
    - type: EmitSoundOnLand
      sound:
        path: /Audio/Items/multitool_drop.ogg
    - type: Sprite
      sprite: _Persistence14/Objects/Tools/grid-configurator.rsi
      state: icon
      layers:
        - state: id
          visible: false
          map: [ "enum.GridConfigVisualLayers.ID" ]
        - state: icon
        - state: screen
          visible: false
          map: [ "enum.GridConfigVisualLayers.Screen" ]
    - type: Item
      size: Small
    - type: Clothing
      sprite: Objects/Tools/access_configurator.rsi
      quickEquip: false
      slots:
        - Belt
    - type: GridConfig
      privilegedIdSlot:
        name: id-card-console-privileged-id
        ejectSound: /Audio/Machines/id_swipe.ogg
        insertSound: /Audio/Weapons/Guns/MagIn/batrifle_magin.ogg
        ejectOnBreak: true
        swap: false
        whitelist:
          components:
          - IdCard
      doAfter: 0.5
    - type: UserInterface
      interfaces:
        enum.GridConfigUiKey.Key:
          type: GridConfigBoundUserInterface
    - type: ActivatableUI
      key: enum.GridConfigUiKey.Key
      requiresComplex: true
      requireActiveHand: false
      singleUser: true
      inHandsOnly: true
    - type: ItemSlots
    - type: ContainerContainer
      containers:
        GridConfig-privilegedId: !type:ContainerSlot
    - type: PhysicalComposition
      materialComposition:
        Plastic: 50
        Steel: 100
    - type: GenericVisualizer
      visuals:
        enum.GridConfigVisuals.HasId:
          enum.GridConfigVisualLayers.ID:
            Id: { visible: true }
            NoId: { visible: false }
        enum.GridConfigVisuals.Screen:
          enum.GridConfigVisualLayers.Screen:
            On: { visible: true }
            Off: { visible: false }
    - type: Appearance