using Content.Client.Humanoid;
using Content.Client.Message;
using Content.Client.Players.PlayTimeTracking;
using Content.Client.Sprite;
using Content.Shared.CCVar;
using Content.Shared.GameTicking;
using Content.Shared.Guidebook;
using Content.Shared.Humanoid;
using Content.Shared.Humanoid.Markings;
using Content.Shared.Preferences;
using Content.Shared._Art.Preferences;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.Player;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Client.Utility;
using Robust.Shared.Configuration;
using Robust.Shared.Console.Commands;
using Robust.Shared.ContentPack;
using Robust.Shared.Enums;
using Robust.Shared.Prototypes;
using System.Linq;
using Direction = Robust.Shared.Maths.Direction;

namespace Content.Client.Lobby.UI
{
    [GenerateTypedNameReferences]
    public sealed partial class HumanoidProfileEditor : BoxContainer
    {
        private readonly IClientPreferencesManager _preferencesManager;
        private readonly IConfigurationManager _cfgManager;
        private readonly IEntityManager _entManager;
        private readonly IFileDialogManager _dialogManager;
        private readonly IPlayerManager _playerManager;
        private readonly IPrototypeManager _prototypeManager;
        private readonly IResourceManager _resManager;
        private readonly MarkingManager _markingManager;
        private readonly JobRequirementsManager _requirements;
        private readonly LobbyUIController _controller;

        private readonly SpriteSystem _sprite;

        // CCvar.
        private int _maxNameLength;

        /// <summary>
        /// If we're attempting to save.
        /// </summary>
        public event Action? Save;

        /// <summary>
        /// If we're attempting to join.
        /// </summary>
        public event Action? Join;

        /// <summary>
        /// Entity used for the profile editor preview
        /// </summary>
        public EntityUid PreviewDummy;


        /// <summary>
        /// The character slot for the current profile.
        /// </summary>
        public int? CharacterSlot;

        // SS14-Art-Edit start
        /// <summary>
        /// What the persistent (saved) body for <see cref="CharacterSlot"/> is currently
        /// wearing, as last reported by the server. Null if there is no saved body yet
        /// (character never entered cryosleep) or we haven't heard back yet.
        /// </summary>
        private Dictionary<string, string>? _persistentEquipment;
        // SS14-Art-Edit end

        /// <summary>
        /// The work in progress profile being edited.
        /// </summary>
        public HumanoidCharacterProfile? Profile;

        private Direction _previewRotation = Direction.North;

        private bool _isDirty;

        public bool IsDirty
        {
            get => _isDirty;
            set
            {
                if (_isDirty == value)
                    return;

                _isDirty = value;
                UpdateSaveButton();
            }
        }

        private ISawmill _sawmill;

		public static readonly (string Name, string Desc)[] Alignments =
		{
			("humanoid-profile-editor-alignment-lawfulgood-name", "humanoid-profile-editor-alignment-lawfulgood-desc"),
			("humanoid-profile-editor-alignment-good-name", "humanoid-profile-editor-alignment-good-desc"),
			("humanoid-profile-editor-alignment-chaoticgood-name", "humanoid-profile-editor-alignment-chaoticgood-desc"),
			("humanoid-profile-editor-alignment-lawful-name", "humanoid-profile-editor-alignment-lawful-desc"),
			("humanoid-profile-editor-alignment-trueneutral-name", "humanoid-profile-editor-alignment-trueneutral-desc"),
			("humanoid-profile-editor-alignment-chaotic-name", "humanoid-profile-editor-alignment-chaotic-desc"),
			("humanoid-profile-editor-alignment-lawfulevil-name", "humanoid-profile-editor-alignment-lawfulevil-desc"),
			("humanoid-profile-editor-alignment-evil-name", "humanoid-profile-editor-alignment-evil-desc"),
			("humanoid-profile-editor-alignment-chaoticevil-name", "humanoid-profile-editor-alignment-chaoticevil-desc"),
		};

		public static readonly (string Name, string Desc)[] Backgrounds =
		{
			("humanoid-profile-editor-bg-corporate-name", "humanoid-profile-editor-bg-corporate-desc"),
			("humanoid-profile-editor-bg-laborworld-name", "humanoid-profile-editor-bg-laborworld-desc"),
			("humanoid-profile-editor-bg-warworld-name", "humanoid-profile-editor-bg-warworld-desc"),
			("humanoid-profile-editor-bg-suburbworld-name", "humanoid-profile-editor-bg-suburbworld-desc"),
			("humanoid-profile-editor-bg-coreworld-name", "humanoid-profile-editor-bg-coreworld-desc"),
			("humanoid-profile-editor-bg-commune-name", "humanoid-profile-editor-bg-commune-desc"),
		};

		public static readonly (string Name, string Desc)[] Motives =
		{
			("humanoid-profile-editor-motive-wealth-name", "humanoid-profile-editor-motive-wealth-desc"),
			("humanoid-profile-editor-motive-power-name", "humanoid-profile-editor-motive-power-desc"),
			("humanoid-profile-editor-motive-knowledge-name", "humanoid-profile-editor-motive-knowledge-desc"),
			("humanoid-profile-editor-motive-friendship-name", "humanoid-profile-editor-motive-friendship-desc"),
			("humanoid-profile-editor-motive-enlightenment-name", "humanoid-profile-editor-motive-enlightenment-desc"),
		};

		public static readonly (string Name, string Desc)[] Sigils =
		{
			("humanoid-profile-editor-sigil-whale-name", "humanoid-profile-editor-sigil-whale-desc"),
			("humanoid-profile-editor-sigil-lock-name", "humanoid-profile-editor-sigil-lock-desc"),
			("humanoid-profile-editor-sigil-show-name", "humanoid-profile-editor-sigil-show-desc"),
			("humanoid-profile-editor-sigil-thought-name", "humanoid-profile-editor-sigil-thought-desc"),
			("humanoid-profile-editor-sigil-void-name", "humanoid-profile-editor-sigil-void-desc"),
		};
        private MarkingsViewModel _markingsModel = new();

        public HumanoidProfileEditor(
            IClientPreferencesManager preferencesManager,
            IConfigurationManager configurationManager,
            IEntityManager entManager,
            IFileDialogManager dialogManager,
            ILogManager logManager,
            IPlayerManager playerManager,
            IPrototypeManager prototypeManager,
            IResourceManager resManager,
            JobRequirementsManager requirements,
            MarkingManager markings)
        {
            RobustXamlLoader.Load(this);
            _sawmill = logManager.GetSawmill("profile.editor");
            _cfgManager = configurationManager;
            _entManager = entManager;
            _dialogManager = dialogManager;
            _playerManager = playerManager;
            _prototypeManager = prototypeManager;
            _markingManager = markings;
            _preferencesManager = preferencesManager;
            // SS14-Art-Edit start
            _preferencesManager.PersistentAppearanceReceived += OnPersistentAppearanceReceived;
            // SS14-Art-Edit end
            _resManager = resManager;
            _requirements = requirements;
            _controller = UserInterfaceManager.GetUIController<LobbyUIController>();
            _sprite = _entManager.System<SpriteSystem>();

            _maxNameLength = _cfgManager.GetCVar(CCVars.MaxNameLength);
            _allowFlavorText = _cfgManager.GetCVar(CCVars.FlavorText);

			TabContainer.SetTabTitle(2, Loc.GetString("humanoid-profile-editor-background-tab"));
			TabContainer.SetTabTitle(3, Loc.GetString("humanoid-profile-editor-threshold-tab"));

			void SetupSelect(OptionButton button, Label title, RichTextLabel desc,
							 (string Name, string Desc)[] items, int initial)
			{
				foreach (var item in items)
					button.AddItem(Loc.GetString(item.Name));

				void Apply(int id)
				{
					var e = items[id];
					title.Text = Loc.GetString(e.Name);
					desc.SetMarkup(Loc.GetString(e.Desc));
					button.SelectId(id);
				}

				button.OnItemSelected += args => Apply(args.Id);
				button.Select(initial);
				Apply(initial);
			}

			SetupSelect(AlignmentButton, AlignTitleLabel, AlignDescLabel, Alignments, 4);
			SetupSelect(BGButton, BGTitleLabel, BGDescLabel, Backgrounds, 0);
			SetupSelect(MotiveButton, MotiveTitleLabel, MotiveDescLabel, Motives, 3);
			SetupSelect(SigilButton, SigilTitle, SigilLabel, Sigils, 0);

			ThresholdLoreLabel.SetMarkup(Loc.GetString("humanoid-profile-editor-threshold-lore"));
			NanotrasenLabel.SetMarkup(Loc.GetString("humanoid-profile-editor-nanotrasen-lore"));

            Markings.SetModel(_markingsModel);

            ImportButton.OnPressed += args =>
            {
                ImportProfile();
            };

            ExportButton.OnPressed += args =>
            {
                ExportProfile();
            };

            ExportImageButton.OnPressed += args =>
            {
                ExportImage();
            };

            OpenImagesButton.OnPressed += args =>
            {
                _resManager.UserData.OpenOsWindow(ContentSpriteSystem.Exports);
            };

            ResetButton.OnPressed += args =>
            {
                SetProfile((HumanoidCharacterProfile?)_preferencesManager.Preferences?.SelectedCharacter, _preferencesManager.Preferences?.SelectedCharacterIndex);
            };

            SaveButton.OnPressed += args =>
            {
                Save?.Invoke();
            };
            JoinGameButton.OnPressed += args =>
            {
                Join?.Invoke();
            };

            #region Left

            #region Name

            NameEdit.OnTextChanged += args => { SetName(args.Text); };
            NameEdit.IsValid = args => args.Length <= _maxNameLength;
            NameRandomize.OnPressed += args => RandomizeName();
            RandomizeEverythingButton.OnPressed += args => { RandomizeEverything(); };
            WarningLabel.SetMarkup($"[color=red]{Loc.GetString("humanoid-profile-editor-naming-rules-warning")}[/color]");

            #endregion Name

            #region Appearance

            TabContainer.SetTabTitle(0, Loc.GetString("humanoid-profile-editor-appearance-tab"));

            #region Sex

            SexButton.OnItemSelected += args =>
            {
                SexButton.SelectId(args.Id);
                SetSex((Sex)args.Id);
            };

            #endregion Sex

            #region Age

            AgeEdit.OnTextChanged += args =>
            {
                if (!int.TryParse(args.Text, out var newAge))
                    return;

                SetAge(newAge);
            };

            #endregion Age

            #region Gender

            PronounsButton.AddItem(Loc.GetString("humanoid-profile-editor-pronouns-male-text"), (int)Gender.Male);
            PronounsButton.AddItem(Loc.GetString("humanoid-profile-editor-pronouns-female-text"), (int)Gender.Female);
            PronounsButton.AddItem(Loc.GetString("humanoid-profile-editor-pronouns-epicene-text"), (int)Gender.Epicene);
            PronounsButton.AddItem(Loc.GetString("humanoid-profile-editor-pronouns-neuter-text"), (int)Gender.Neuter);

            PronounsButton.OnItemSelected += args =>
            {
                PronounsButton.SelectId(args.Id);
                SetGender((Gender)args.Id);
            };

            #endregion Gender

            RefreshSpecies();

            SpeciesButton.OnItemSelected += args =>
            {
                SpeciesButton.SelectId(args.Id);
                SetSpecies(_species[args.Id].ID);
                OnSkinColorOnValueChanged();
            };

            #region Skin

            Skin.OnValueChanged += _ =>
            {
                OnSkinColorOnValueChanged();
            };

            RgbSkinColorContainer.AddChild(_rgbSkinColorSelector = new ColorSelectorSliders());
            _rgbSkinColorSelector.SelectorType = ColorSelectorSliders.ColorSelectorType.Hsv; // defaults color selector to HSV
            _rgbSkinColorSelector.OnColorChanged += _ =>
            {
                OnSkinColorOnValueChanged();
            };

            #endregion

            #region SpawnPriority

            foreach (var value in Enum.GetValues<SpawnPriorityPreference>())
            {
                SpawnPriorityButton.AddItem(Loc.GetString($"humanoid-profile-editor-preference-spawn-priority-{value.ToString().ToLower()}"), (int)value);
            }

            SpawnPriorityButton.OnItemSelected += args =>
            {
                SpawnPriorityButton.SelectId(args.Id);
                SetSpawnPriority((SpawnPriorityPreference)args.Id);
            };

            #endregion SpawnPriority

            #region Eyes

            EyeColorPicker.OnEyeColorPicked += newColor =>
            {
                if (Profile is null)
                    return;
                Profile = Profile.WithCharacterAppearance(
                    Profile.Appearance.WithEyeColor(newColor));
                _markingsModel.SetOrganEyeColor(Profile.Appearance.EyeColor);
                ReloadProfilePreview();
            };

            #endregion Eyes

            #endregion Appearance

            #region Jobs

            TabContainer.SetTabTitle(1, Loc.GetString("humanoid-profile-editor-markings-tab"));

            _jobCategories = new Dictionary<string, BoxContainer>();

            RefreshAntags();
            RefreshJobs();

            #endregion Jobs


            RefreshTraits();

            #region Markings


            _markingsModel.MarkingsChanged += (_, _) => OnMarkingChange();
            _markingsModel.MarkingsReset += OnMarkingChange;

            #endregion Markings

            RefreshFlavorText();

            #region Dummy

            SpriteRotateLeft.OnPressed += _ =>
            {
                _previewRotation = _previewRotation.TurnCw();
                SetPreviewRotation(_previewRotation);
            };
            SpriteRotateRight.OnPressed += _ =>
            {
                _previewRotation = _previewRotation.TurnCcw();
                SetPreviewRotation(_previewRotation);
            };

            #endregion Dummy

            #endregion Left

            ShowClothes.OnToggled += args =>
            {
                ReloadPreview();
            };

            SpeciesInfoButton.OnPressed += OnSpeciesInfoButtonPressed;

            UpdateSpeciesGuidebookIcon();
            if (Profile == null)
            {
                Profile = new HumanoidCharacterProfile();
                RandomizeEverything();
            }
            SetDirty();
        }

        /// <summary>
        /// Refreshes the flavor text editor status.
        /// </summary>
        //public void RefreshFlavorText()
        //{
        //    if (_allowFlavorText)
        //    {
        //        if (_flavorText != null)
        //            return;

        //        _flavorText = new FlavorText.FlavorText();
        //        TabContainer.AddChild(_flavorText);
        //        TabContainer.SetTabTitle(TabContainer.ChildCount - 1, Loc.GetString("humanoid-profile-editor-flavortext-tab"));
        //        _flavorTextEdit = _flavorText.CFlavorTextInput;

        //        _flavorText.OnFlavorTextChanged += OnFlavorTextChange;
        //    }
        //    else
        //    {
        //        if (_flavorText == null)
        //            return;

        //        TabContainer.RemoveChild(_flavorText);
        //        _flavorText.OnFlavorTextChanged -= OnFlavorTextChange;
        //        _flavorText.Dispose();
        //        _flavorTextEdit?.Dispose();
        //        _flavorTextEdit = null;
        //        _flavorText = null;
        //    }
        //}

        /// <summary>
        /// Refreshes traits selector
        /// </summary>
        //public void RefreshTraits()
        //{

        //}

        /// <summary>
        /// Refreshes the species selector.
        /// </summary>
        //public void RefreshSpecies()
        //{
        //    SpeciesButton.Clear();
        //    _species.Clear();

        //    _species.AddRange(_prototypeManager.EnumeratePrototypes<SpeciesPrototype>().Where(o => o.RoundStart));
        //    _species.Sort((a, b) => string.Compare(a.Name, b.Name, StringComparison.CurrentCultureIgnoreCase));
        //    var speciesIds = _species.Select(o => o.ID).ToList();

        //    for (var i = 0; i < _species.Count; i++)
        //    {
        //        var name = Loc.GetString(_species[i].Name);
        //        SpeciesButton.AddItem(name, i);

        //        if (Profile?.Species.Equals(_species[i].ID) == true)
        //        {
        //            SpeciesButton.SelectId(i);
        //        }
        //    }

        //    // If our species isn't available then reset it to default.
        //    if (Profile != null)
        //    {
        //        if (!speciesIds.Contains(Profile.Species))
        //        {
        //            SetSpecies(SharedHumanoidAppearanceSystem.DefaultSpecies);
        //        }
        //    }
        //}

        //public void RefreshAntags()
        //{

        //}

        private void SetDirty()
        {
            if (Profile == null)
            {
                Profile = new HumanoidCharacterProfile();
                RandomizeEverything();
            }

            // Creating new character
            if (_preferencesManager.Preferences?.SelectedCharacter == null)
            {
                IsDirty = true;

                TabContainer.Visible = true;

                SaveButton.Visible = true;
                JoinGameButton.Visible = false;

                ImportButton.Visible = true;
                ExportButton.Visible = false;
                OpenImagesButton.Visible = false;
                ExportImageButton.Visible = false;

                NameRandomize.Visible = true;
                RandomizeEverythingButton.Visible = true;
                ResetButton.Visible = false;
                NameEdit.Editable = true;
            }
            // Opening existing chracter
            else
            {
                IsDirty = false;

                TabContainer.Visible = false;

                SaveButton.Visible = false;
                JoinGameButton.Visible = true;

                ImportButton.Visible = false;
                ExportButton.Visible = true;
                OpenImagesButton.Visible = true;
                ExportImageButton.Visible = true;

                RandomizeEverythingButton.Visible = false;
                NameRandomize.Visible = false;
                ResetButton.Visible = false;
                NameEdit.Editable = false;
            }
        }

        /// <summary>
        /// Reloads the entire dummy entity for preview.
        /// </summary>
        /// <remarks>
        /// This is expensive so not recommended to run if you have a slider.
        /// </remarks>
        public void ReloadPreview()
        {
            if (Profile == null)
                return;

            SpriteView.LoadPreview(Profile, JobOverride, ShowClothes.Pressed, _persistentEquipment); // SS14-Art-Edit: _persistentEquipment

            // Check and set the dirty flag to enable the save/reset buttons as appropriate.
            SetDirty();
        }

        /// <summary>
        /// Resets the profile to the defaults.
        /// </summary>
        public void ResetToDefault()
        {
            SetProfile(
                (HumanoidCharacterProfile?)_preferencesManager.Preferences?.SelectedCharacter,
                _preferencesManager.Preferences?.SelectedCharacterIndex);
        }

        /// <summary>
        /// Sets the editor to the specified profile with the specified slot.
        /// </summary>
        public void SetProfile(HumanoidCharacterProfile? profile, int? slot)
        {
            Profile = profile?.Clone();
            CharacterSlot = slot;
            SetDirty();
            JobOverride = null;

            // SS14-Art-Edit start
            // Try to get cached equipment from CharacterSetupGui first
            if (slot != null)
            {
                var parent = Parent;
                while (parent != null && parent is not CharacterSetupGui)
                    parent = parent.Parent;
                
                if (parent is CharacterSetupGui setupGui)
                {
                    // Use cached equipment immediately if available
                    _persistentEquipment = setupGui.GetPersistentEquipment(slot.Value);
                }
                else
                {
                    _persistentEquipment = null;
                }
                
                // Always request fresh data from server
                _preferencesManager.RequestPersistentAppearance(slot.Value);
            }
            else
            {
                _persistentEquipment = null;
            }
            // SS14-Art-Edit end

            UpdateNameEdit();
            UpdateFlavorTextEdit();
            UpdateSexControls();
            UpdateGenderControls();
            UpdateSkinColor();
            UpdateSpawnPriorityControls();
            UpdateAgeEdit();
            UpdateEyePickers();
            UpdateSaveButton();
            UpdateMarkings();

            RefreshAntags();
            RefreshJobs();
            RefreshLoadouts();
            RefreshSpecies();
            RefreshTraits();
            RefreshFlavorText();
            ReloadPreview();

            //if (Profile != null)
            //{
            //    PreferenceUnavailableButton.SelectId((int)Profile.PreferenceUnavailable);
            //}
        }

        /// <summary>
        /// A slim reload that only updates the entity itself and not any of the job entities, etc.
        /// </summary>
        private void ReloadProfilePreview()
        {
            if (Profile == null)
                return;

            SpriteView.ReloadProfilePreview(Profile);

            // Check and set the dirty flag to enable the save/reset buttons as appropriate.
            SetDirty();
        }

        // SS14-Art-Edit start
        private void OnPersistentAppearanceReceived(MsgPersistentAppearance message)
        {
            // Stale response for a slot we've since navigated away from - ignore it.
            if (message.Slot != CharacterSlot)
                return;

            _persistentEquipment = message.Found ? message.EquippedItems : null;
            ReloadPreview();
        }
        // SS14-Art-Edit end

        //private void OnSpeciesInfoButtonPressed(BaseButton.ButtonEventArgs args)
        //{
        //    // TODO GUIDEBOOK
        //    // make the species guide book a field on the species prototype.
        //    // I.e., do what jobs/antags do.

        //    var guidebookController = UserInterfaceManager.GetUIController<GuidebookUIController>();
        //    var species = Profile?.Species ?? SharedHumanoidAppearanceSystem.DefaultSpecies;
        //    var page = DefaultSpeciesGuidebook;
        //    if (_prototypeManager.HasIndex<GuideEntryPrototype>(species))
        //        page = new ProtoId<GuideEntryPrototype>(species.Id); // Gross. See above todo comment.

        //    if (_prototypeManager.Resolve(DefaultSpeciesGuidebook, out var guideRoot))
        //    {
        //        var dict = new Dictionary<ProtoId<GuideEntryPrototype>, GuideEntry>();
        //        dict.Add(DefaultSpeciesGuidebook, guideRoot);
        //        //TODO: Don't close the guidebook if its already open, just go to the correct page
        //        guidebookController.OpenGuidebook(dict, includeChildren:true, selected: page);
        //    }
        //}

        /// <summary>
        /// Refreshes all job selectors.
        /// </summary>
        //public void RefreshJobs()
        //{

        //}

        //private void OpenLoadout(JobPrototype? jobProto, RoleLoadout roleLoadout, RoleLoadoutPrototype roleLoadoutProto)
        //{
        //    _loadoutWindow?.Dispose();
        //    _loadoutWindow = null;
        //    var collection = IoCManager.Instance;

        //    if (collection == null || _playerManager.LocalSession == null || Profile == null)
        //        return;

        //    JobOverride = jobProto;
        //    var session = _playerManager.LocalSession;

        //    _loadoutWindow = new LoadoutWindow(Profile, roleLoadout, roleLoadoutProto, _playerManager.LocalSession, collection)
        //    {
        //        Title = Loc.GetString("loadout-window-title-loadout", ("job", $"{jobProto?.LocalizedName}")),
        //    };

        //    // Refresh the buttons etc.
        //    _loadoutWindow.RefreshLoadouts(roleLoadout, session, collection);
        //    _loadoutWindow.OpenCenteredLeft();

        //    _loadoutWindow.OnNameChanged += name =>
        //    {
        //        roleLoadout.EntityName = name;
        //        Profile = Profile.WithLoadout(roleLoadout);
        //        SetDirty();
        //    };

        //    _loadoutWindow.OnLoadoutPressed += (loadoutGroup, loadoutProto) =>
        //    {
        //        roleLoadout.AddLoadout(loadoutGroup, loadoutProto, _prototypeManager);
        //        _loadoutWindow.RefreshLoadouts(roleLoadout, session, collection);
        //        Profile = Profile?.WithLoadout(roleLoadout);
        //        ReloadPreview();
        //    };

        //    _loadoutWindow.OnLoadoutUnpressed += (loadoutGroup, loadoutProto) =>
        //    {
        //        roleLoadout.RemoveLoadout(loadoutGroup, loadoutProto, _prototypeManager);
        //        _loadoutWindow.RefreshLoadouts(roleLoadout, session, collection);
        //        Profile = Profile?.WithLoadout(roleLoadout);
        //        ReloadPreview();
        //    };

        //    JobOverride = jobProto;
        //    ReloadPreview();

        //    _loadoutWindow.OnClose += () =>
        //    {
        //        JobOverride = null;
        //        ReloadPreview();
        //    };

        //    if (Profile is null)
        //        return;

        //    UpdateJobPriorities();
        //}

        //private void OnFlavorTextChange(string content)
        //{
        //    if (Profile is null)
        //        return;

        //    Profile = Profile.WithFlavorText(content);
        //    SetDirty();
        //}

        //private void OnMarkingChange(MarkingSet markings)
        //{
        //    if (Profile is null)
        //        return;

        //    Profile = Profile.WithCharacterAppearance(Profile.Appearance.WithMarkings(markings.GetForwardEnumerator().ToList()));
        //    ReloadProfilePreview();
        //}

        //private void OnSkinColorOnValueChanged()
        //{
        //    if (Profile is null) return;

        //    var skin = _prototypeManager.Index<SpeciesPrototype>(Profile.Species).SkinColoration;
        //    var strategy = _prototypeManager.Index(skin).Strategy;

        //    switch (strategy.InputType)
        //    {
        //        case SkinColorationStrategyInput.Unary:
        //        {
        //            if (!Skin.Visible)
        //            {
        //                Skin.Visible = true;
        //                RgbSkinColorContainer.Visible = false;
        //            }

        //            var color = strategy.FromUnary(Skin.Value);

        //            Markings.CurrentSkinColor = color;
        //            Profile = Profile.WithCharacterAppearance(Profile.Appearance.WithSkinColor(color));

        //            break;
        //        }
        //        case SkinColorationStrategyInput.Color:
        //        {
        //            if (!RgbSkinColorContainer.Visible)
        //            {
        //                Skin.Visible = false;
        //                RgbSkinColorContainer.Visible = true;
        //            }

        //            var color = strategy.ClosestSkinColor(_rgbSkinColorSelector.Color);

        //            Markings.CurrentSkinColor = color;
        //            Profile = Profile.WithCharacterAppearance(Profile.Appearance.WithSkinColor(color));

        //            break;
        //        }
        //    }

        //    ReloadProfilePreview();
        //}

        protected override void Dispose(bool disposing)
        {
            base.Dispose(disposing);
            if (!disposing)
                return;

            // SS14-Art-Edit start
            _preferencesManager.PersistentAppearanceReceived -= OnPersistentAppearanceReceived;
            // SS14-Art-Edit end

            _loadoutWindow?.Dispose();
            _loadoutWindow = null;
        }

        protected override void EnteredTree()
        {
            base.EnteredTree();
            ReloadPreview();
        }

        private void UpdateSaveButton()
        {
            SaveButton.Disabled = Profile is null || !IsDirty;
            ResetButton.Disabled = Profile is null || !IsDirty;
        }

        private void SetPreviewRotation(Direction direction)
        {
            SpriteView.OverrideDirection = (Direction)((int)direction % 4 * 2);
        }

        //private void RandomizeEverything()
        //{
        //    if(Profile != null)
        //         Profile = HumanoidCharacterProfile.RandomWithSpecies(Profile.Species);
        //    else
        //        Profile = HumanoidCharacterProfile.Random();
        //    SetProfile(Profile, CharacterSlot);
        //    SetDirty();
        //}

        //private void RandomizeName()
        //{
        //    if (Profile == null) return;
        //    var name = HumanoidCharacterProfile.GetName(Profile.Species, Profile.Gender);
        //    SetName(name);
        //    UpdateNameEdit();
        //}


    }
}
