using Content.Client.Message;
using Content.Shared.Cargo;
using Content.Shared.Cargo.Prototypes;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using System.Linq;

namespace Content.Client.Cargo.UI;

[GenerateTypedNameReferences]
public sealed partial class BountyEntry : BoxContainer
{
    [Dependency] private readonly IEntityManager _entityManager = default!;
    [Dependency] private readonly IPrototypeManager _prototype = default!;

    public Action? OnLabelButtonPressed;
    public Action? OnSkipButtonPressed;

    public TimeSpan EndTime;
    public TimeSpan UntilNextSkip;

    public BountyEntry(CargoBountyData bounty, TimeSpan untilNextSkip)
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        UntilNextSkip = untilNextSkip;

        if (!_prototype.Resolve<CargoBountyPrototype>(bounty.Bounty, out var bountyPrototype))
            return;
        IdLabel.SetMarkup(Loc.GetString("bounty-console-id-label", ("id", bounty.Id)));
        var items = new List<string>();
        foreach (var entry in bountyPrototype.Condition.GetManifestEntry(_entityManager, _prototype))
        {
            items.Add(entry);
        }
        ManifestLabel.SetMarkup(Loc.GetString("bounty-console-manifest-label", ("item", string.Join(", ", items))));
        DescriptionLabel.SetMarkup(Loc.GetString("bounty-console-description-label", ("description", Loc.GetString(bountyPrototype.Description))));
        LevelBar.Visible = true;

        var hasPricePer = bountyPrototype.Condition.TryGetPricePer(bountyPrototype.Reward, out var pricePer, out var unitName);

        RewardLabel.SetMarkup(Loc.GetString("bounty-total-value",
            ("reward", bountyPrototype.Reward.ToString("F2")),
            ("hasPricePer", hasPricePer),
            ("pricePer", pricePer.ToString("F2")),
            ("unit", unitName ?? "")
            ));
        LevelBar.MaxValue = 1f;
        LevelBar.Value = bounty.PercentCompleted;
        LevelBarText.Text = $"{bounty.PercentCompleted:P2}";
        PrintButton.OnPressed += _ => OnLabelButtonPressed?.Invoke();
    }
}
