- type: entity
  id: SolarLegionTechFabCircuitboard
  parent: BaseMachineCircuitboard
  name: solar legion techfab machine board
  description: A machine printed circuit board for a solar legion techfab.
  components:
    - type: Sprite
      state: command
    - type: MachineBoard
      prototype: SolarLegionTechFab
      stackRequirements:
        Manipulator: 4
      tagRequirements:
        GlassBeaker:
          amount: 2
          defaultPrototype: Beaker

- type: entity
  id: ColdplateMachineCircuitboard
  parent: BaseMachineCircuitboard
  name: coldplate machine board
  description: A machine printed circuit board for a coldplate.
  components:
  - type: Sprite
    state: medical
  - type: MachineBoard
    prototype: ChemistryColdplate
    stackRequirements:
      Manipulator: 2
      Glass: 1
