name: "Labels: Branch staging-unstable"

on:
  pull_request_target:
    types:
      - opened
    branches:
      - 'staging-unstable'

jobs:
  add_label:
    runs-on: ubuntu-latest
    steps:
    - uses: actions-ecosystem/action-add-labels@v1
      with:
        labels: "pr-unstable"
