name: Publish EU

on:
  workflow_dispatch:
  schedule:
    # To run before EU shifts. Scheduled at 15:00 UTC
    - cron: '0 15 * * 1,6'

jobs:
  publish:
    uses: ./.github/workflows/publish-base.yml
    with:
      source_ref: server-eu
      fork_id: pss14-eu
    secrets: inherit