name: Publish US

on:
  workflow_dispatch:
  schedule:
    # To run before US shifts. Scheduled at 20:00 UTC
    - cron: '0 20 * * 0,3'

jobs:
  publish:
    uses: ./.github/workflows/publish-base.yml
    with:
      source_ref: server-us
      fork_id: pss14-us
    secrets: inherit